export const holidays = [
    { date: "1 Jan", day: "Monday", Name: "New Year's Day", type: "Public Holiday" },
    { date: "12 Feb", day: "Monday", Name: "Family Day (BC)", type: "Regional Holiday" },
    { date: "19 Feb", day: "Monday", Name: "Family Day (AB, BC, NB, ON, SK)", type: "Regional Holiday" },
    { date: "19 Feb", day: "Monday", Name: "Islander Day (PE)", type: "Regional Holiday" },
    { date: "19 Feb", day: "Monday", Name: "Louis Riel Day (MB)", type: "Regional Holiday" },
    { date: "29 Mar", day: "Friday", Name: "Good Friday", type: "Public Holiday" },
    { date: "1 Apr", day: "Monday", Name: "Easter Monday", type: "Public Holiday" },
    { date: "20 May", day: "Monday", Name: "Victoria Day", type: "Public Holiday" },
    { date: "21 Jun", day: "Friday", Name: "National Indigenous Peoples Day", type: "Observance" },
    { date: "1 Jul", day: "Monday", Name: "Canada Day", type: "Public Holiday" },
    { date: "5 Aug", day: "Monday", Name: "Civic Holiday", type: "Regional Holiday" },
    { date: "2 Sep", day: "Monday", Name: "Labour Day", type: "Public Holiday" },
    { date: "14 Oct", day: "Monday", Name: "Thanksgiving Day", type: "Public Holiday" },
    { date: "11 Nov", day: "Monday", Name: "Remembrance Day", type: "Public Holiday" },
    { date: "25 Dec", day: "Wednesday", Name: "Christmas Day", type: "Public Holiday" },
    { date: "26 Dec", day: "Thursday", Name: "Boxing Day", type: "Public Holiday" },
];
